Feature/components - Milestone 2
ClintonEnyinna/react_calculator pull request #3
Opened 2020-06-24 06:59 UTC by ClintonEnyinna

The following where implemented: 

- [ ] App component
- [ ] Display component
- [ ] Button component
- [ ] ButtonPanel component

2020-06-24 12:02 UTC, shloch requested changes
## hello @ClintonEnyinna , 

Great job really...just some more validation to do

### [changes required]
check my comments below

2020-06-24 12:02 UTC, shloch commented on src/components/Display.jsx
> +export default Display;
- enforce `result` to be a String with `propTypes` [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)]

- enforce `result` to have default valu of `'0'` with `defaultProps` [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png)]

2020-06-24 12:02 UTC, shloch commented on src/components/Button.jsx
> +export default Button;
- enforce `name` to be string with `propTypes` [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/validateAsString.png)]

2020-06-26 07:33 UTC, fatymahmed approved these changes
### Hi @ClintonEnyinna,
Great job making the requested changes 🎉🎉

- Please make sure you use gitflow for the other milestones in this project as mentioned on pathwright ![Screenshot from 2020-06-26 10-29-15](https://user-images.githubusercontent.com/16196289/85832095-20b70a00-b798-11ea-9c90-001f38fba32d.png)

## status: Approved ✔️

2020-06-26 16:14 UTC, merged